### PR TITLE
fix: L2NativeSuperchainERC20 token addr and update docs

### PR DESCRIPTION
**Pull request by jakim929**
closes https://github.com/ethereum-optimism/supersim/issues/152

long term we need to think of a better solution, created an issue [here](https://github.com/ethereum-optimism/supersim/issues/154)

### CODE REVIEW

**Comment by jakim929** [comment]
* **#153** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/supersim/153?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jakim929 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by jakim929** [comment]
* **#153** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/supersim/153?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jakim929 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by jakim929** [comment]
* **#153** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/supersim/153?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jakim929 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by tremarkley — APPROVED** [review]

**Comment by jakim929** [comment]
* **#153** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/supersim/153?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jakim929 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Pull request merged**
