### PR TITLE
💅 refactor L2NativeSuperchainERC20 and SuperchainWETH logging

### PR DESCRIPTION
**Pull request by tabshaikh**
**Description**

updated L2NativeSuperchainERC20 and SuperchainWETH to use similar logging

**Metadata**

https://github.com/ethereum-optimism/supersim/issues/144

### CODE REVIEW

**Review by jakim929 — CHANGES_REQUESTED** [review]
I should have specified it better in the issue, but I think a cleaner approach is to use the SuperchainERC20 binding for both contracts since they share the same interface (bindings/superchainerc20.go). 

Roughly something like
```go
opSim.bgTasks.Go(func() error {
    contracts := []struct {
        name    string
        address common.Address
    }{
        {"SuperchainWETH", predeploys.SuperchainWETHAddr},
        {"L2NativeSuperchainERC20", common.HexToAddress(l2NativeSuperchainERC20Addr)},
    }

    for _, c := range contracts {
        contract, err := bindings.NewSuperchainERC20(c.address, opSim.Chain.EthClient())
        if err != nil {
            return fmt.Errorf("failed to create %s contract: %w", c.name, err)
        }

        mintEventChan := make(chan *bindings.SuperchainERC20CrosschainMint)
        burnEventChan := make(chan *bindings.SuperchainERC20CrosschainBurn)

        mintSub, err := contract.WatchCrosschainMint(&bind.WatchOpts{Context: opSim.bgTasksCtx}, mintEventChan, nil)
        if err != nil {
            return fmt.Errorf("failed to subscribe to %s#CrosschainMint: %w", c.name, err)
        }

        burnSub, err := contract.WatchCrosschainBurn(&bind.WatchOpts{Context: opSim.bgTasksCtx}, burnEventChan, nil)
        if err != nil {
            return fmt.Errorf("failed to subscribe to %s#CrosschainBurn: %w", c.name, err)
        }
...
```

Please let me know if I can provide any more context

**Comment by tabshaikh** [comment]
@jakim929 pushed changes using `SuperchainERC20`. Was previously abstracting a lot because thought there were no common interface but as they both use `ICrosschainERC20` things are much cleaner

**Review by jakim929 — APPROVED** [review]

**Comment by jakim929** [comment]
@tabshaikh thanks this looks great! good to go once CI passes

**Comment by tabshaikh** [comment]
weirdly the admin test was failing fixed that
Screenshot 2024-11-09 at 1 40 28 AM

**Pull request merged**
